%%高斯
n=0:63;
p=8;
q=2;
x=exp(-1*(n-p).^2/q);
X=fft(x);
Xdef=fft_def(x);
subplot(3,1,1);stem(x);
title('原序列');
subplot(3,1,2);stem(abs(Xdef));
title('自定义FFT');
subplot(3,1,3);stem(abs(X));
title('系统FFT');
sgtitle('高斯序列');
set(gcf,'position',[0,0,1000,1000]);
saveas(gcf,'gaosi.jpg');

figure
a=0.1;
f=0.0625;
x=exp(-1*a*n).*(sin(2*pi*f*n));
X=fft(x);
Xdef=fft_def(x);
subplot(3,1,1);stem(x);
title('原序列');
subplot(3,1,2);stem(abs(Xdef));
title('自定义FFT');
subplot(3,1,3);stem(abs(X));
title('系统FFT');
sgtitle('正弦衰减序列');
set(gcf,'position',[0,0,1000,1000]);
saveas(gcf,'expsin.jpg');

figure
x=ones(1,64);
X=fft(x);
Xdef=fft_def(x);
subplot(3,1,1);stem(x);
title('原序列');
subplot(3,1,2);stem(abs(Xdef));
title('自定义FFT');
subplot(3,1,3);stem(abs(X));
title('系统FFT');
sgtitle('矩形脉冲序列');
set(gcf,'position',[0,0,1000,1000]);
saveas(gcf,'juxing.jpg');

